const classes=[
 {id:1,title:'فیزیوتراپی سبک',aud:'سالمندان',gender:'بانوان',duration:2,cap:5,hours:'۰۸:۰۰–۲۲:۰۰',closed:'۱۲:۰۰–۱۴:۰۰',tags:['elderly','women'],days:'هر روز'},
 {id:2,title:'فیزیوتراپی سبک',aud:'سالمندان',gender:'آقایان',duration:2,cap:5,hours:'۰۸:۰۰–۲۲:۰۰',closed:'۱۲:۰۰–۱۴:۰۰',tags:['elderly','men'],days:'هر روز'},
 {id:3,title:'فعالیت‌های سبک',aud:'سالمندان',gender:'بانوان',duration:2,cap:6,hours:'۰۸:۰۰–۲۲:۰۰',closed:'۱۲:۰۰–۱۵:۰۰',tags:['elderly','women'],days:'هر روز'},
 {id:4,title:'فعالیت‌های سبک',aud:'سالمندان',gender:'آقایان',duration:2,cap:6,hours:'۰۸:۰۰–۲۲:۰۰',closed:'۱۲:۰۰–۱۵:۰۰',tags:['elderly','men'],days:'هر روز'},
 {id:5,title:'کلاس قرآن',aud:'۸ تا ۵۰ سال',gender:'بانوان',duration:2,cap:36,hours:'۱۰:۰۰–۲۰:۰۰',closed:'۱۲:۰۰–۱۳:۰۰',tags:['women'],days:'روزهای زوج',holiday:true},
 {id:6,title:'کلاس قرآن',aud:'۸ تا ۵۰ سال',gender:'آقایان',duration:2,cap:36,hours:'۱۰:۰۰–۲۰:۰۰',closed:'۱۲:۰۰–۱۳:۰۰',tags:['men'],days:'روزهای فرد',holiday:true},
 {id:7,title:'کلاس تذهیب و نگارگری',aud:'بین‌نسلی',gender:'بانوان',duration:2,cap:24,hours:'۱۰:۰۰–۲۲:۰۰',closed:'۱۲:۰۰–۱۴:۰۰',tags:['inter','women','art'],days:'روزهای زوج',holiday:true},
 {id:8,title:'کلاس تذهیب و نگارگری',aud:'بین‌نسلی',gender:'آقایان',duration:2,cap:24,hours:'۱۰:۰۰–۲۲:۰۰',closed:'۱۲:۰۰–۱۴:۰۰',tags:['inter','men','art'],days:'روزهای فرد',holiday:true},
 {id:9,title:'کلاس بافتنی',aud:'بین‌نسلی',gender:'بانوان',duration:3,cap:20,hours:'۰۸:۰۰–۲۳:۰۰',closed:'۱۲:۰۰–۱۳:۰۰',tags:['inter','women','art'],days:'هر روز',holiday:true},
 {id:10,title:'کلاس گلدوزی',aud:'بین‌نسلی',gender:'بانوان',duration:3,cap:16,hours:'۰۸:۰۰–۲۳:۰۰',closed:'۱۲:۰۰–۱۳:۰۰',tags:['inter','women','art'],days:'هر روز',holiday:true},
 {id:11,title:'کلاس خوشنویسی',aud:'۸ تا ۶۰ سال',gender:'بانوان',duration:3,cap:12,hours:'۰۸:۰۰–۲۴:۰۰',closed:'۱۲:۰۰–۱۳:۰۰',tags:['women','art'],days:'روزهای زوج',holiday:true},
 {id:12,title:'کلاس خوشنویسی',aud:'۸ تا ۶۰ سال',gender:'آقایان',duration:3,cap:12,hours:'۰۸:۰۰–۲۴:۰۰',closed:'۱۲:۰۰–۱۳:۰۰',tags:['men','art'],days:'روزهای فرد',holiday:true},
 {id:13,title:'کلاس نقاشی',aud:'۸ تا ۶۰ سال',gender:'بانوان',duration:3,cap:14,hours:'۰۸:۰۰–۲۴:۰۰',closed:'۱۲:۰۰–۱۴:۰۰',tags:['women','art'],days:'روزهای زوج',holiday:true},
 {id:14,title:'کلاس نقاشی',aud:'۸ تا ۶۰ سال',gender:'آقایان',duration:3,cap:14,hours:'۰۸:۰۰–۲۴:۰۰',closed:'۱۲:۰۰–۱۴:۰۰',tags:['men','art'],days:'روزهای فرد',holiday:true}
];
const pageNames={home:'خانه',idea:'ایده پروژه',generations:'نسل‌ها',program:'برنامه مرکز',gallery:'گالری',library:'کتابخانه',research:'پژوهش',faq:'سؤالات معماری',project:'مشخصات پروژه'};
const faqData=[
 {cat:'کانسپت و ایده',q:'کانسپت اصلی پروژه چیست؟',a:'کانسپت پروژه بر تبدیل «مشارکت بین‌نسلی» از یک مفهوم نظری به یک ساختار فضایی واقعی استوار است؛ به‌گونه‌ای که نسل‌های مختلف علاوه بر فضاهای اختصاصی، در فضاهای مشترک نیز امکان تعامل داشته باشند.'},
 {cat:'کانسپت و ایده',q:'چگونه مفهوم بین‌نسلی در معماری پروژه نمود پیدا کرده است؟',a:'با ایجاد فضاهای مشترک، فعالیت‌های جمعی و فضاهایی برای گفت‌وگو، یادگیری و انتقال تجربه میان گروه‌های سنی مختلف.'},
 {cat:'کانسپت و ایده',q:'چرا فضاهای مشترک در این پروژه اهمیت دارند؟',a:'برای اینکه نسل‌های مختلف فقط در یک مجموعه حضور نداشته باشند، بلکه بتوانند با یکدیگر تعامل، یادگیری و مشارکت واقعی داشته باشند.'},
 {cat:'طراحی معماری',q:'سازماندهی فضایی پروژه بر چه اساسی شکل گرفته است؟',a:'بر پایه ارتباط میان فضاهای آموزشی، فرهنگی، اجتماعی و فضاهای باز و نیمه‌باز تا حرکت، مکث و تعامل کاربران میان بخش‌های مختلف تسهیل شود.'},
 {cat:'طراحی معماری',q:'انعطاف‌پذیری در پروژه چگونه ایجاد شده است؟',a:'با پیش‌بینی فضاهای چندمنظوره و امکان تغییر نحوه استفاده و چیدمان فضاها برای فعالیت‌های مختلف.'},
 {cat:'طراحی معماری',q:'تفاوت طراحی فضای سالمندان و کودکان چیست؟',a:'برای سالمندان بر مسیر خوانا، نشیمن و فضای آرام تأکید شده و برای کودکان بر بازی، فعالیت و دیدپذیری؛ در کنار آن فضاهای مشترک برای ارتباط نسل‌ها پیش‌بینی شده است.'},
 {cat:'طراحی معماری',q:'یادگیری در پروژه فقط در کلاس اتفاق می‌افتد؟',a:'خیر؛ یادگیری در گالری، حیاط، مسیر، کارگاه و فضاهای مشترک نیز اتفاق می‌افتد و معماری نقش بستر یادگیری غیررسمی را پیدا می‌کند.'},
 {cat:'اقلیم و کیفیت',q:'رویکرد اقلیمی پروژه در شهر قم چیست؟',a:'توجه به سایه، کنترل تابش، نور طبیعی، فضاهای نیمه‌باز و آسایش حرارتی با توجه به اقلیم گرم و خشک قم.'},
 {cat:'اقلیم و کیفیت',q:'چرا فضاهای نیمه‌باز در پروژه اهمیت دارند؟',a:'برای ایجاد واسطه میان فضای داخلی و خارجی، بهبود کیفیت حضور کاربران و هم‌زمان پاسخ‌گویی به نیازهای اقلیمی و اجتماعی.'},
 {cat:'اقلیم و کیفیت',q:'مهم‌ترین معیارهای طراحی پروژه چه هستند؟',a:'ارتباط بین نسل‌ها، خوانایی و دسترسی، انعطاف‌پذیری، نور طبیعی، کنترل تابش، آسایش حرارتی، پایداری، فضاهای باز آموزشی، تعامل اجتماعی و طراحی بدون مانع.'}
];
let selectedClass=null;
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
function route(name){if(!pageNames[name])name='home';qsa('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));qsa('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===name));document.title=(pageNames[name]==='خانه'?'مرکز فرهنگی با تأکید بر مشارکت بین‌نسلی | قم':pageNames[name]+' | مرکز فرهنگی بین‌نسلی');window.scrollTo({top:0,behavior:'instant'});qs('.main-nav')?.classList.remove('open');qs('.menu-toggle')?.setAttribute('aria-expanded','false');if(name==='faq')renderFaq('همه');}
function storage(){try{return JSON.parse(localStorage.getItem('mb_reservations')||'{}')}catch{return{}}}
function save(o){try{localStorage.setItem('mb_reservations',JSON.stringify(o))}catch{}}
function remaining(c){const r=storage();return Math.max(0,c.cap-Number(r[c.id]||0));}
function renderPrograms(filter='all'){const grid=qs('#programGrid');if(!grid)return;const list=classes.filter(c=>filter==='all'||c.tags.includes(filter));grid.innerHTML=list.map(c=>{const rem=remaining(c),pct=Math.max(0,Math.min(100,rem/c.cap*100));return `<article class="program-card"><div class="program-top"><span class="program-kind">${c.tags.includes('inter')?'INTERGENERATIONAL':'CLASS'}</span><span class="program-kind">#${String(c.id).padStart(2,'0')}</span></div><h3>${c.title}</h3><div class="program-meta">${c.aud} · ${c.gender}<br>${c.duration} ساعت در هر جلسه · ${c.days}</div><div class="program-badges"><span class="badge">${c.hours}</span><span class="badge">تعطیلی: ${c.closed}</span>${c.holiday?'<span class="badge">تعطیلات رسمی: تعطیل</span>':''}</div><div class="session-row"><div><strong>ظرفیت ${c.cap}</strong><br><small>${rem} نفر باقی‌مانده</small></div><strong>${c.duration}h</strong></div><div class="capacity-mini"><span style="width:${pct}%"></span></div><button class="btn btn-dark register" data-id="${c.id}" ${rem===0?'disabled':''}>${rem===0?'تکمیل ظرفیت':'ثبت‌نام جلسه'}</button></article>`}).join('');qsa('.register').forEach(b=>b.addEventListener('click',()=>openModal(Number(b.dataset.id))));}
function openModal(id){selectedClass=classes.find(c=>c.id===id);if(!selectedClass)return;const rem=remaining(selectedClass);qs('#modalTitle').textContent=selectedClass.title+' · '+selectedClass.gender;qs('#modalMeta').textContent=`${selectedClass.aud} · هر جلسه ${selectedClass.duration} ساعت · ${selectedClass.days} · ${selectedClass.hours}`;qs('#modalRemaining').textContent=rem;qs('#capacityFill').style.width=Math.max(0,Math.min(100,rem/selectedClass.cap*100))+'%';qs('#confirmRegister').disabled=rem===0;qs('#confirmRegister').textContent=rem===0?'ظرفیت تکمیل است':'ثبت‌نام در جلسه';qs('#registerModal').classList.add('open');qs('#registerModal').setAttribute('aria-hidden','false')}
function closeModal(){qs('#registerModal').classList.remove('open');qs('#registerModal').setAttribute('aria-hidden','true')}
function renderFaq(cat='همه'){const grid=qs('#faqQuestions');if(!grid)return;const list=faqData.filter(x=>cat==='همه'||x.cat===cat);grid.innerHTML=list.map((x,i)=>`<button class="faq-question" data-faq-index="${faqData.indexOf(x)}"><span>${String(faqData.indexOf(x)+1).padStart(2,'0')}</span><strong>${x.q}</strong><b>↗</b></button>`).join('');qsa('.faq-question').forEach(btn=>btn.addEventListener('click',()=>showFaq(Number(btn.dataset.faqIndex))));}
function showFaq(i){const item=faqData[i];if(!item)return;qs('#faqAnswerTitle').textContent=item.q;qs('#faqAnswerText').textContent=item.a;qs('#faqAnswerCat').textContent=item.cat;qs('#faqAnswer').classList.add('show');qsa('.faq-question').forEach(b=>b.classList.toggle('selected',Number(b.dataset.faqIndex)===i));setTimeout(()=>qs('#faqAnswer')?.scrollIntoView({behavior:'smooth',block:'nearest'}),40)}
qsa('[data-route]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const n=a.dataset.route;location.hash=n;route(n)}));
window.addEventListener('hashchange',()=>route(location.hash.slice(1)||'home'));
qsa('.filter').forEach(b=>b.addEventListener('click',()=>{qsa('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPrograms(b.dataset.filter)}));
qsa('.faq-category').forEach(b=>b.addEventListener('click',()=>{qsa('.faq-category').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderFaq(b.dataset.faqCategory);qs('#faqAnswer').classList.remove('show')}));
qs('#modalClose')?.addEventListener('click',closeModal);qs('.modal-backdrop')?.addEventListener('click',closeModal);
qs('#confirmRegister')?.addEventListener('click',()=>{if(!selectedClass)return;const r=storage();if(Number(r[selectedClass.id]||0)<selectedClass.cap){r[selectedClass.id]=Number(r[selectedClass.id]||0)+1;save(r);renderPrograms(qs('.filter.active')?.dataset.filter||'all');closeModal();setTimeout(()=>alert('ثبت‌نام آزمایشی با موفقیت ثبت شد.'),20)}});
qs('.menu-toggle')?.addEventListener('click',()=>qs('.main-nav').classList.toggle('open'));
function setToday(){const d=new Date();const day=['یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه','شنبه'][d.getDay()];if(qs('#todayLabel'))qs('#todayLabel').textContent='امروز · '+day}
qsa('.gallery-card').forEach(card=>card.addEventListener('click',()=>{const title=card.querySelector('h3')?.textContent||'گالری';qs('#lightboxTitle').textContent=title;const visual=qs('#lightboxVisual');const img=card.querySelector('.gallery-visual img');if(img){visual.className='lightbox-visual gallery-image';visual.innerHTML='<img src="'+img.getAttribute('src')+'" alt="'+(img.getAttribute('alt')||title)+'">';}else{visual.innerHTML='';visual.className='lightbox-visual '+(card.querySelector('.gallery-visual')?.classList.contains('v1')?'v1':card.querySelector('.gallery-visual')?.classList.contains('v2')?'v2':'v3');}qs('#lightbox').classList.add('open')}));
qs('#lightboxClose')?.addEventListener('click',()=>qs('#lightbox').classList.remove('open'));qs('#lightbox')?.addEventListener('click',e=>{if(e.target.id==='lightbox'||e.target.classList.contains('lightbox-backdrop'))qs('#lightbox').classList.remove('open')});
renderPrograms();setToday();renderFaq();route(location.hash.slice(1)||'home');

window.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(qs('#registerModal')?.classList.contains('open'))closeModal();if(qs('#lightbox')?.classList.contains('open'))qs('#lightbox').classList.remove('open');if(qs('.main-nav')?.classList.contains('open')){qs('.main-nav').classList.remove('open');qs('.menu-toggle')?.setAttribute('aria-expanded','false')}});
